export const MonthTypes = {
  SET_MONTH_DATA: 'SET_MONTH_DATA',
  DELETE_TASK: 'DELETE_TASK',
  SET_CURRENT_MONTH: 'SET_TITLE_OF_MONTH',
  ADD_TASK_TO_DAY: 'ADD_TASK_TO_DAY',
  SET_DAYS: 'SET_DAYS',
  ADD_POINTS: 'ADD_POINTS',
  REMOVE_POINTS: 'REMOVE_POINTS',
  SET_COMPLETED: 'SET_COMPLETED',
  RESET_MONTH: 'RESET_MONTH',
  SWITCH_MONTH: 'SWITCH_MONTH',
};
