export const CategoriesTypes = {
  ADD_NEW_CATEGORY: 'ADD_NEW_CATEGORY',
  REMOVE_CATEGORY: 'REMOVE_CATEGORY',
  ADD_TIME_TO_CATEGORY: 'ADD_TIME_TO_CATEGORY',
  REMOVE_TIME_FROM_CATEGORY: 'REMOVE_TIME_FROM_CATEGORY',
  LOAD_CATEGORY_DATA: 'LOAD_CATEGORY_DATA',
  RESET_CATEGORY_DATA: 'RESET_CATEGORY_DATA',
  SWITCH_CATEGORIES: 'SWITCH_CATEGORIES',
};
